### ISSUE TITLE
Errors after upgrade to 2.9.0

### ISSUE THREAD

**Issue by EdwardMoyse** [ATLAS-experiment/PhoenixATLAS#18]
I did:
```
yarn upgrade phoenix-event-display@latest phoenix-ui-components@latest
```

And now `yarn deploy` fails with:
```
Error: src/app/pages/atlas/atlas.component.ts:43:9 - error TS2554: Expected 4 arguments, but got 3.

43         new PresetView('Left View', [0, 0, -12000], 'left-cube'),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'll investigate updating the code now.
